# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_t2',
                'doc_host': 'https://cronbi.github.io',
                'git_url': 'https://github.com/cronbi/nbdev_t2',
                'lib_path': 'nbdev_t2'},
  'syms': {'nbdev_t2.core': {'nbdev_t2.core.foo': ('core.html#foo', 'nbdev_t2/core.py')}}}
